### ISSUE TITLE
Error - cannot get response

### ISSUE THREAD

**Issue by iamLiquidX** [roofman2008/Pahe.ph-Scraper#5]
I am trying with ur latest release of 2 days ago 2.1 alpha.
![IMG_20211122_124305](https://user-images.githubusercontent.com/66400864/142819067-bd1daf12-dfc1-4def-b79a-b876a8f6885a.jpg)
Any help?

**Comment by roofman2008** [comment]
I'm checking this issue and i will release new patches

**Comment by roofman2008** [comment]
@iamLiquidX Check now the new version and if the problem still exist, send here the log file "log.txt" from the scraper root folder so i could study.
https://github.com/roofman2008/Pahe.ph-Scraper/releases/tag/Alpha-2.2

**Comment by iamLiquidX** [comment]
> @iamLiquidX Check now the new version and if the problem still exist, send here the log file "log.txt" from the scraper root folder so i could study. https://github.com/roofman2008/Pahe.ph-Scraper/releases/tag/Alpha-2.3

i have tried with 2.2 and 2.3 . i am attaching log of both. still no success in running. hopes this helps in debugging.

[log 2.2.txt](https://github.com/roofman2008/Pahe.ph-Scraper/files/7585747/log.2.2.txt)
[log 2.3.txt](https://github.com/roofman2008/Pahe.ph-Scraper/files/7585748/log.2.3.txt)

**Comment by roofman2008** [comment]
@iamLiquidX in config file "PaheScrapper.exe.config", modify this property to False and send me GIF or Video for what is happening on Chrome.
`<setting name="WebDriveHeadless" serializeAs="String">
                <value>False</value>
            </setting>`

What is happening that cookie bypass is not working and that what is happening is this log line


`<html><title>You are being redirected...</title>
<noscript>Javascript is required. Please enable javascript before you are allowed to see this page.</noscript>
<script>var s={},u,c,U,r,i,l=0,a,e=eval,w=String.fromCharCode,sucuri_cloudproxy_js='',S='bj0nbkBlJy5jaGFyQXQoMikrJ0plJy5zbGljZSgxLDIpKyI3IiArICdiJyArICAgJycgKyAKIjgiICsgICcnICsnJysnWXJRZScuc3Vic3RyKDMsIDEpICsiOHNlYyIuc3Vic3RyKDAsMSkgKyBTdHJpbmcuZnJvbUNoYXJDb2RlKDQ5KSArICIiICsiYSIgKyBTdHJpbmcuZnJvbUNoYXJDb2RlKDEwMikgKyAnNycgKyAgIiIgKyJhc2VjIi5zdWJzdHIoMCwxKSArICJlc3UiLnNsaWNlKDAsMSkgKyAiMyIgKyAnZicgKyAgICcnICsgCiJjIi5zbGljZSgwLDEpICsgJzcnICsgICIwIiArICAnJyArIAondFI4Jy5jaGFyQXQoMikrImYiLnNsaWNlKDAsMSkgKyAiIiArImMiICsgICcnICsnZFE5Jy5jaGFyQXQoMikrIjEiLnNsaWNlKDAsMSkgKyAiNyIgKyAnOScgKyAgICcnICsnJysiZHN1Ii5zbGljZSgwLDEpICsgJ3c8MCcuY2hhckF0KDIpKyIiICsnZVM3Jy5jaGFyQXQoMikrImJzZWMiLnN1YnN0cigwLDEpICsgICcnICsnJysnS3pQNicuc3Vic3RyKDMsIDEpICsnSmFIMScuc3Vic3RyKDMsIDEpICsiIiArU3RyaW5nLmZyb21DaGFyQ29kZSg1MikgKyAgJycgKycnO2RvY3VtZW50LmNvb2tpZT0nc3N1Jy5jaGFyQXQoMCkgKyd1c3VjdXJpJy5jaGFyQXQoMCkgKyAnYycrJ3N1Y3V1Jy5jaGFyQXQoNCkrICdycycuY2hhckF0KDApKydpJysnJysnXycrJycrJ3N1YycuY2hhckF0KDIpKydzdWwnLmNoYXJBdCgyKSsnb3N1YycuY2hhckF0KDApKyAndXMnLmNoYXJBdCgwKSsnZCcuY2hhckF0KDApKydwJysncnN1YycuY2hhckF0KDApKyAnbycrJycrJ3gnKycnKyd5JysnXycrJ3VzdWN1cmknLmNoYXJBdCgwKSArICd1c3VjdScuY2hhckF0KDApICArJ3N1Y3VpJy5jaGFyQXQoNCkrICdkJysnJysnXycrJ2InKyc5Jysnc3U1Jy5jaGFyQXQoMikrJ2EnLmNoYXJBdCgwKSsnMCcuY2hhckF0KDApKycwJysnMHN1Jy5jaGFyQXQoMCkgKydzdTUnLmNoYXJBdCgyKSsnNCcuY2hhckF0KDApKyI9IiArIG4gKyAnO3BhdGg9LzttYXgtYWdlPTg2NDAwJzsgbG9jYXRpb24ucmVsb2FkKCk7';L=S.length;U=0;r='';var A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';for(u=0;u<64;u++){s[A.charAt(u)]=u;}for(i=0;i<L;i++){c=s[S.charAt(i)];U=(U<<6)+c;l+=6;while(l>=8){((a=(U>>>(l-=8))&0xff)||(i<(L-2)))&&(r+=w(a));}}e(r);</script></html>
`

**Comment by iamLiquidX** [comment]
> @iamLiquidX in config file "PaheScrapper.exe.config", modify this property to False and send me GIF or Video for what is happening on Chrome.
> 
> ```
> <setting name="WebDriveHeadless" serializeAs="String">
>                 <value>False</value>
>             </setting>
> ```
> 
> What is happening that cookie bypass is not working and that what is happening in this log line
> 
> **Compressed**
> 
> ```
> Log Entry: 5:59 AM 11/23/2021 - Html Dump: 
> PAcAAB+LCAAAAAAABACFVWtzojwY/d5f4acVR9cqaLcdwBmKN1BoK/UCOzs7EChGQmC5SLHb/74B7cXqO+8HJ5g8zznnOXmScOvERz0ugQlyenqQVszIqVgOxG4lcmwYOSBx7GazyV3uQy44HMQggmHSk82tuf+swJhE/0lJuN2s3CPHjJ2Kg00LOZXNR5TlPAUEPT+wmAgFmWNXkqASO04lWROU0HQdwvXOccEdPrZmVIn5l9dG2gCNeSNqwAbiWw2z4fDO1kSNjNeSiKhuPkWBL67NSAxspxGnII3gb4CC1A6j4Dn/vYn5arWh8VVr08KWd4vkvLsxR8P8YfUQKNCL5FZYzO2sEdoYmvs87UvhJJcYCQqRJNpQzotRcOUcuJNcmEgbF0pi7EoiwGTEch7j5UqeGRpIAbOAgJnlk74SS/1BSNbh3VhFei59WhNiRfMI1u2jPZZDywepgeWtNVcDfSX3LXqGJv2H7kQreKWCC+qa9D/xg4zUUujD6l6nSzLJKK8BvdhIsLuzl/LOHkuBImbPe2wZAWYOp1iNzaWKPnQJUMmlEsuAB6x9ra4I5RLr4FU23dfoyrv9OtGb7X0TcOmbEGB7KHW+ei75+lneMtdXjvw1hoPuSf5mcDZfPei+0450F3sEjbHaPqudAdeKCFKdXq+BN2xN9vsPS+6Fwpxql3fGUin42zpWWwB+YH3uCY0JH1R4tiew5g8l5T/6pfBgTubMZRdPfSO36Ha/5KdvPKK7fdjnQz8CfEfPtjqzSIxltzX11a1FJ6Hx2MKAUdtH2sUiz24Tzo29ksPTNQHrOYhkkkfwjnJV0SvOQg7yzz4JxCc7LGotfqsi9y0//+qnTfovI/WUPXtri24+0WJsncQWmAK2V8rn2KyINcQT7qzgBfg8hvWux8WFTyS++66TWRA9ahv43hee8szvPdKOMUlPv3kTnvHGO/KBlgrOko+csfbJnUMPTupTTuoDZX3K+Ow+7uzH+Ymf6gmGdFOeqVFnfy6Y27U9cm+muyTRV26iL210/+jSal/I5F3sWqObjb6ahRbdSYG/iC166E1E70eVnfJaEznYTdbsnG+xEblU2eKKFviqcCv2B8PRWJInU0W9u3+YaY/zxXKlG6YFbOfJXcONh3wchH+iOEm32XO+a7VpptO9+nF9U7+ssuSVoFKCmnJXHTat12sv8U+hCcilLiRUWvvFp+xrEQNJDOSmLCxCAB//1N6CYO0X0UXNOe6qVgcsqvNXbLaGyKFQj7+uvVCUSVZ7vR6FvpP/tW+t56en2t+/FOSo6Xe6Rma+UVGdzyizVmNfXx0qqrHc5eEt4i7LR/PiHwG2tqY8BwAA
> ```
> 
> **Decompressed**
> 
> ```
> Log Entry: 5:59 AM 11/23/2021 - Html Dump: <html><title>You are being redirected...</title>
> <noscript>Javascript is required. Please enable javascript before you are allowed to see this page.</noscript>
> <script>var s={},u,c,U,r,i,l=0,a,e=eval,w=String.fromCharCode,sucuri_cloudproxy_js='',S='bj0nbkBlJy5jaGFyQXQoMikrJ0plJy5zbGljZSgxLDIpKyI3IiArICdiJyArICAgJycgKyAKIjgiICsgICcnICsnJysnWXJRZScuc3Vic3RyKDMsIDEpICsiOHNlYyIuc3Vic3RyKDAsMSkgKyBTdHJpbmcuZnJvbUNoYXJDb2RlKDQ5KSArICIiICsiYSIgKyBTdHJpbmcuZnJvbUNoYXJDb2RlKDEwMikgKyAnNycgKyAgIiIgKyJhc2VjIi5zdWJzdHIoMCwxKSArICJlc3UiLnNsaWNlKDAsMSkgKyAiMyIgKyAnZicgKyAgICcnICsgCiJjIi5zbGljZSgwLDEpICsgJzcnICsgICIwIiArICAnJyArIAondFI4Jy5jaGFyQXQoMikrImYiLnNsaWNlKDAsMSkgKyAiIiArImMiICsgICcnICsnZFE5Jy5jaGFyQXQoMikrIjEiLnNsaWNlKDAsMSkgKyAiNyIgKyAnOScgKyAgICcnICsnJysiZHN1Ii5zbGljZSgwLDEpICsgJ3c8MCcuY2hhckF0KDIpKyIiICsnZVM3Jy5jaGFyQXQoMikrImJzZWMiLnN1YnN0cigwLDEpICsgICcnICsnJysnS3pQNicuc3Vic3RyKDMsIDEpICsnSmFIMScuc3Vic3RyKDMsIDEpICsiIiArU3RyaW5nLmZyb21DaGFyQ29kZSg1MikgKyAgJycgKycnO2RvY3VtZW50LmNvb2tpZT0nc3N1Jy5jaGFyQXQoMCkgKyd1c3VjdXJpJy5jaGFyQXQoMCkgKyAnYycrJ3N1Y3V1Jy5jaGFyQXQoNCkrICdycycuY2hhckF0KDApKydpJysnJysnXycrJycrJ3N1YycuY2hhckF0KDIpKydzdWwnLmNoYXJBdCgyKSsnb3N1YycuY2hhckF0KDApKyAndXMnLmNoYXJBdCgwKSsnZCcuY2hhckF0KDApKydwJysncnN1YycuY2hhckF0KDApKyAnbycrJycrJ3gnKycnKyd5JysnXycrJ3VzdWN1cmknLmNoYXJBdCgwKSArICd1c3VjdScuY2hhckF0KDApICArJ3N1Y3VpJy5jaGFyQXQoNCkrICdkJysnJysnXycrJ2InKyc5Jysnc3U1Jy5jaGFyQXQoMikrJ2EnLmNoYXJBdCgwKSsnMCcuY2hhckF0KDApKycwJysnMHN1Jy5jaGFyQXQoMCkgKydzdTUnLmNoYXJBdCgyKSsnNCcuY2hhckF0KDApKyI9IiArIG4gKyAnO3BhdGg9LzttYXgtYWdlPTg2NDAwJzsgbG9jYXRpb24ucmVsb2FkKCk7';L=S.length;U=0;r='';var A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';for(u=0;u<64;u++){s[A.charAt(u)]=u;}for(i=0;i<L;i++){c=s[S.charAt(i)];U=(U<<6)+c;l+=6;while(l>=8){((a=(U>>>(l-=8))&0xff)||(i<(L-2)))&&(r+=w(a));}}e(r);</script></html>
> ```

So i ran it with suggested edit , it opened chrome as it should but it closed it right away while the pahe.ph was loading, then it opened it again and this time the scrapping process has started.

![Screenshot_2021-11-24-07-48-04-178_com microsoft rdc androidx](https://user-images.githubusercontent.com/66400864/143159561-eca4e385-246b-45df-8ea4-0a8cfac57ba5.jpg)

I will attach a video if it is still needed.

**Comment by roofman2008** [comment]
Ok it's working now, later I will release new patch for bypass mechanism #8

**Comment by iamLiquidX** [comment]
> Ok it's working now, later I will release new patch for bypass mechanism #8

happiness didn't last long.

Error -Length cannot be less than zero.
Parameter name: length

logs 
[log.txt](https://github.com/roofman2008/Pahe.ph-Scraper/files/7592390/log.txt)
-

**Comment by roofman2008** [comment]
This case due to empty page, it willl be solved in the next version Alpha 2.4.

**Comment by roofman2008** [comment]
@iamLiquidX Check the latest version 
PaheScraper Alpha 2.4 (Windows): https://github.com/roofman2008/Pahe.ph-Scraper/releases/tag/Alpha-2.4

**Comment by iamLiquidX** [comment]
> @iamLiquidX Check the latest version PaheScraper Alpha 2.4 (Windows): https://github.com/roofman2008/Pahe.ph-Scraper/releases/tag/Alpha-2.4

Working flawlessly. i will report if i face any error.
