### ISSUE TITLE
Error - given key was not present in the dictionary.

### ISSUE THREAD

**Issue by iamLiquidX** [roofman2008/Pahe.ph-Scraper#9]
here are the logs for debugging.

[log.txt](https://github.com/roofman2008/Pahe.ph-Scraper/files/7600145/log.txt)

**Comment by roofman2008** [comment]
Solved in the upcoming release Alpha 2.5, wait the build soon.

**Comment by iamLiquidX** [comment]
> Solved in the upcoming release Alpha 2.5, wait the build soon. I made a complete Details Phase Test and all issues solved.

Waiting....

**Comment by roofman2008** [comment]
HYG, the new version
https://github.com/roofman2008/Pahe.ph-Scraper/releases/tag/Alpha-2.5

**Comment by iamLiquidX** [comment]
Will test and report.
